@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

@route = http://{{host}}


GET {{route}}/api/countries


###

GET {{route}}/api/capitals/
Accept: application/json

###
GET {{route}}/api/capitals/1

###

GET {{route}}/api/cities/

###
GET {{route}}/api/cities/

###

POST {{route}}/api/cities/
Content-Type: application/json

{
    "name": "Dhaka",
    "country": "Bangladesh"
}





