name: CI/CD

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, CI/CD!"
      - name: Run a one-line script
        run: echo "Hello, CI/CD again!"
      - name: Run a test
        run: echo "Running a test"

      - name: Test status
        run: echo "Test status, passed"
       
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, CI/CD!"

      #- name: Simulate an error
      #  run: echo "About to fail"; exit 1
      - name: Another greeting
        run: echo "Hello, CI/CD again!"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
      - name: Deployment status 
        run: deployment passed
        
        